"""add posts

Revision ID: 92d1c3fe2f71
Revises: 81e9c8d0d793
Create Date: 2020-05-04 18:52:29.389036

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92d1c3fe2f71"
down_revision = "81e9c8d0d793"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_timestamp"), "posts", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_timestamp"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
