---
apiVersion: v1
kind: Secret
metadata:
  name: myq5-secret
  labels:
    app: myq5-web-app
type: Opaque
data:
  MYQ5_SECRET_KEY: {{ base64 secret }}
  MYQ5_EMAIL_ADDRESS: {{ base64 secret }}
  MYQ5_EMAIL_PASSWORD: {{ base64 secret }}
  MYQ5_DATABASE_URL: {{ base64 secret }}
  MYQ5_ADMIN_EMAIL_ADDRESS: {{ base64 secret }}